name: Deploy site to GitHub Pages
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 
        run: |      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install --no-fund --no-audit
      - run: npx @11ty/eleventy --input=src --output=_site --formats=njk,md,html --quiet=false --verbose
          mkdir -p _site
          cat > _site/index.html << 'HTML'
          <!doctype html>
          <meta charset="utf-8">
          <title>AOE is live ✅</title>
          <h1>AOE is live ✅</h1>
          <p>If you see this, GitHub Pages is working.</p>
          <p>Next: we’ll turn Eleventy back on.</p>
          HTML
      - uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
