name: Deploy site to GitHub Pages
on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Make a simple site (test Pages)
        run: |
          mkdir -p _site
          printf '%s\n' \
            '<!doctype html>' \
            '<meta charset="utf-8">' \
            '<title>AOE is live ✅</title>' \
            '<h1>AOE is live ✅</h1>' \
            '<p>If you see this, GitHub Pages is working.</p>' \
            > _site/index.html
      - uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
